CATEGORIAS_GASTO = (
    "Mercado", "Transporte", "Servicios", "Ocio", "Salud", "Otros",
    "Hogar", "Seguridad Social", "Administracion", "Suscripciones",
    "Tarjeta", "Celular", "GYM", "Ahorro", "Deuda",
)
CATEGORIAS_INGRESO = ("Salario", "Freelance")
CATEGORIAS_TODAS = CATEGORIAS_GASTO + CATEGORIAS_INGRESO

# Palabras clave en minusculas, mas especificas primero.
# ORDEN IMPORTA: las categorias mas especificas van primero para evitar
# que una generica capture antes (ej. "Servicios" no debe capturar "arriendo"
# que ahora va en "Hogar").
KEYWORDS_CATEGORIA: list[tuple[str, tuple[str, ...]]] = [
    # --- Categorias especificas nuevas (capturan antes) ---
    (
        "Hogar",
        (
            "arriendo",
            "alquiler",
            "coninsa",
            "inmobiliaria",
            "canon",
        ),
    ),
    (
        "Seguridad Social",
        (
            "seguridad social",
            "pension",
            "arl",
            "aportes salud",
            "aportes seguridad",
        ),
    ),
    (
        "Administracion",
        (
            "administracion",
            "administración",
            "conjunto",
            "propiedad horizontal",
        ),
    ),
    (
        "Suscripciones",
        (
            "netflix",
            "spotify",
            "disney",
            "apple one",
            "youtube premium",
            "youtube family",
            "hbo",
            "prime video",
            "amazon prime",
            "claude",
            "chatgpt",
            "adobe",
            "gamepass",
            "xbox",
            "steam",
            "cursor",
            "render",
        ),
    ),
    (
        "Tarjeta",
        (
            "tdc",
            "tarjeta de credito",
            "tarjeta credito",
            "nubank",
            "cuota tarjeta",
            "addi",
            "pago tarjeta",
            "intereses corrientes",
            "extracto",
        ),
    ),
    (
        "Celular",
        (
            "celular",
            "plan de datos",
            "plan datos",
            "claro",
            "movistar",
            "tigo",
            "simcard",
            "comcel",
        ),
    ),
    (
        "GYM",
        (
            "gym",
            "gimnasio",
            "smartfit",
            "atletic",
            "bodytech",
        ),
    ),
    (
        "Ahorro",
        (
            "ahorro",
            "ahorrar",
            "ahorre",
            "cdt",
            "fondo de ahorro",
            "fondo emergencia",
            "afc",
        ),
    ),
    (
        "Deuda",
        (
            "deuda",
            "prestamo",
            "préstamo",
            "cuota prestamo",
            "abono deuda",
            "pago mama",
            "pago mamá",
        ),
    ),
    # --- Categorias originales (orden de especificidad) ---
    (
        "Transporte",
        (
            "transmilenio",
            "transmi",
            "uber",
            "didi",
            "cabify",
            "taxi",
            "gasolina",
            "parqueadero",
            "pasaje",
            "sitp",
            "syt",
            "bus",
            "metro",
            "peaje",
        ),
    ),
    (
        "Salud",
        (
            "farmacia",
            "drogueria",
            "droguería",
            "medico",
            "médico",
            "doctor",
            "eps",
            "medicina",
            "consulta",
            "cita medica",
            "cita médica",
            "hospital",
            "farmatodo",
        ),
    ),
    (
        "Servicios",
        (
            "internet",
            "wifi",
            "luz",
            "energia",
            "energía",
            "agua",
            "gas natural",
            "enel",
            "vanti",
            "acueducto",
            "servicios publicos",
        ),
    ),
    (
        "Ocio",
        (
            "cine",
            "bar",
            "cerveza",
            "restaurante",
            "concierto",
            "ocio",
            "juego",
            "fiesta",
            "salida",
            "trago",
            "discoteca",
        ),
    ),
    (
        "Mercado",
        (
            "supermercado",
            "alkosto",
            "mercado",
            "almuerzo",
            "desayuno",
            "comida",
            "cena",
            "corabastos",
            "exito",
            "éxito",
            "jumbo",
            "d1",
            "ara",
            "olimpica",
            "olímpica",
            "carulla",
            "fruver",
            "tienda",
            "oxxo",
        ),
    ),
    # --- Ingresos ---
    (
        "Salario",
        (
            "salario",
            "sueldo",
            "nomina",
            "nómina",
            "me pagaron",
            "me pago",
            "me pagó",
            "quincena",
            "kamecol",
        ),
    ),
    (
        "Freelance",
        (
            "freelance",
            "proyecto",
            "cliente",
            "factura",
            "honorarios",
        ),
    ),
]

KEYWORDS_INGRESO = (
    "me pagaron",
    "me pagó",
    "me pago",
    "recibí",
    "recibi",
    "ingreso",
    "sueldo",
    "salario",
    "nómina",
    "nomina",
    "quincena",
    "kamecol",
    "freelance",
    "honorarios",
)

KEYWORDS_COMPARTIDO = (
    "compartido",
    "entre los dos",
    "mitad",
    "50/50",
    "a medias",
)
